# Generated by Django 3.2.9 on 2021-11-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=17)),
                ('location', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=18)),
                ('id_number_receiver', models.IntegerField()),
                ('email_sender', models.EmailField(max_length=254)),
                ('email_receiver', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now=True)),
                ('parcel_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
