# Generated by Django 3.1.4 on 2021-11-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelapp', '0002_auto_20211128_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='email_receiver',
            new_name='email_of_receiver',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='email_sender',
            new_name='email_of_sender',
        ),
    ]
