# Generated by Django 3.1.4 on 2021-11-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelapp', '0003_auto_20211128_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='category',
            field=models.CharField(choices=[('Small Electronic', 'Small Electronic'), ('Envelope', 'Envelope'), ('Big electronic', 'Big electronic'), ('Food', 'Food')], max_length=17),
        ),
    ]
