# Generated by Django 3.1.4 on 2021-11-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelapp', '0004_auto_20211128_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='id_number_receiver',
            field=models.PositiveIntegerField(),
        ),
    ]
