# Generated by Django 3.1.4 on 2021-12-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelapp', '0005_auto_20211128_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='id_number_sender',
            field=models.PositiveIntegerField(default=566677),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
