# Generated by Django 3.2.9 on 2021-12-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelapp', '0006_auto_20211204_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='status',
            field=models.CharField(default='Transit', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
