# Generated by Django 3.2.9 on 2022-01-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelapp', '0007_auto_20211211_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='status_alert',
            field=models.CharField(default='Alert', max_length=16),
            preserve_default=False,
        ),
    ]
