# Generated by Django 3.2.9 on 2022-04-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelapp', '0008_parcel_status_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='location',
            new_name='from_location',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status_alert',
            field=models.CharField(max_length=20),
        ),
    ]
